### ISSUE TITLE
ValueError: cannot reshape array of size 15264 into shape (3,5)

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#25]
[File](https://drive.google.com/file/d/1JLJyHqnP2DSDcK5i8G3raruEi32mhDBh/view?usp=sharing) (not including textures)
```
Converting /home/heath/luigi/dae/edit/course.dae... 
Traceback (most recent call last):
  File "/home/heath/Downloads/abmatt/abmatt/gui/converter.py", line 67, in run
    self.item.convert()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_lib.py", line 203, in convert
    self.load_model()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 32, in load_model
    self.__parse_nodes(dae.get_scene(), material_geometry_map, matrix)
ValueError: cannot reshape array of size 15264 into shape (3,5)
```

**Comment by Heath123** [comment]
This is Luigi Circuit exported, edited very slightly to test it and reimported

**Comment by Heath123** [comment]
It happens here (why do the tracebacks seem to be broken?)
https://github.com/Robert-N7/abmatt/blob/fbdfae8fb0a39cea79b26b4de38f8f16e7946bab/abmatt/converters/dae.py#L272

**Comment by Heath123** [comment]
Line 1722 of the DAE files seems to be causing a problem

**Comment by Heath123** [comment]
I think it's because it assumes the offsets for the inputs go 1, 2, 3 etc. like this:
```xml
          <input semantic="VERTEX" offset="0" source="#polygon1-VERTEX"/>
          <input semantic="COLOR" offset="1" source="#polygon1-COLOR"/>
          <input semantic="TEXCOORD" offset="2" source="#polygon1-UV0" set="0"/>
          <input semantic="TEXCOORD" offset="3" source="#polygon1-UV1" set="1"/>
```
but in this file they go
```xml
          <input semantic="VERTEX" source="#polygon1_005-mesh-vertices" offset="0"/>
          <input semantic="NORMAL" source="#polygon1_005-mesh-normals" offset="1"/>
          <input semantic="TEXCOORD" source="#polygon1_005-mesh-map-0" offset="2" set="0"/>
          <input semantic="TEXCOORD" source="#polygon1_005-mesh-map-1" offset="2" set="1"/>
          <input semantic="COLOR" source="#polygon1_005-mesh-colors-polygon1-COLOR" offset="3" set="0"/>
```

**Comment by Heath123** [comment]
So it assumes the length is a multiple of len(inputs) when it should be a multiple of the highest offset?

**Comment by Robert-N7** [comment]
That's correct, I've just updated the master branch with the fix.

**Comment by Heath123** [comment]
Thank you!
