### ISSUE TITLE
KeyError: 'beginner_course'

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#27]
Using the same file as in #25, I get this:
```
Converting /home/heath/luigi/dae/edit/course.dae... 
Traceback (most recent call last):
  File "/home/heath/Downloads/abmatt/abmatt/gui/converter.py", line 67, in run
    self.item.convert()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_lib.py", line 195, in convert
    self.load_model()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 33, in load_model
    self.__parse_controllers(material_geometry_map)
KeyError: 'beginner_course'
```

**Comment by Heath123** [comment]
Wait, I might be using the wrong version

**Comment by Heath123** [comment]
I was, sorry
