### ISSUE TITLE
AttributeError: 'InfluenceCollection' object has no attribute 'combine'

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#31]
```
Converting /home/heath/luigi/dae2/edit/course.dae... 
Traceback (most recent call last):
  File "/home/heath/Downloads/abmatt/abmatt/gui/converter.py", line 68, in run
    self.item.convert()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_lib.py", line 197, in convert
    self.load_model()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 35, in load_model
    self.__parse_controllers(material_geometry_map)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 105, in __parse_controllers
    self.__parse_controller(controller, matrix, material_geometry_map)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 109, in __parse_controller
    self.__add_geometry(geometry, material_geometry_map)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 137, in __add_geometry
    if not geo[0].combine(geometry):
  File "/home/heath/Downloads/abmatt/abmatt/converters/geometry.py", line 49, in combine
    self.influences.combine(geometry.influences)
AttributeError: 'InfluenceCollection' object has no attribute 'combine'
```

**Comment by Heath123** [comment]
Model:
[course.zip](https://github.com/Robert-N7/abmatt/files/6310622/course.zip)
