### ISSUE TITLE
ValueError: Unsupported draw cmd 0

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#34]
When converting the [Halogen Highway](http://wiki.tockdom.com/wiki/Halogen_Highway) BRRES file (the Discord download) to DAE:
```
Exporting to /home/heath/mk-plugin/halogen-dae/course.dae...
Traceback (most recent call last):
  File "/home/heath/Downloads/abmatt/abmatt/gui/converter.py", line 68, in run
    self.item.convert()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_lib.py", line 199, in convert
    self.save_model()
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 52, in save_model
    mesh.add_node(self.__decode_geometry(polygon))
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 77, in __decode_geometry
    geo = decode_polygon(polygon, self.influences)
  File "/home/heath/Downloads/abmatt/abmatt/converters/geometry.py", line 417, in decode_polygon
    face_point_indices, weights = decode_indices(polygon, polygon.encode_str)
  File "/home/heath/Downloads/abmatt/abmatt/converters/geometry.py", line 355, in decode_indices
    raise ValueError('Unsupported draw cmd {}'.format(cmd))
ValueError: Unsupported draw cmd 0
```

**Comment by Robert-N7** [comment]
That file seems to be corrupt, it's also missing images and when I try exporting using brawlbox, nothing shows up. I might try to handle the error more gracefully.

**Comment by Heath123** [comment]
Ah, it does work in game though

**Comment by Robert-N7** [comment]
When I open it in brawlbox or with my tool the textures don't show up. The files for the main model seem to be in the vrcorn_model?
