### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#68]
```
Converting /tmp/course.dae... 
Traceback (most recent call last):
  File "/home/heath/Downloads/abmatt/abmatt/__main__.py", line 29, in <module>
    main()
  File "/home/heath/Downloads/abmatt/abmatt/__main__.py", line 22, in main
    files = load_config.parse_args(argv, base_path)
  File "/home/heath/Downloads/abmatt/abmatt/load_config.py", line 358, in parse_args
    if not Command.run_commands(cmds):
  File "/home/heath/Downloads/abmatt/abmatt/command.py", line 705, in run_commands
    cmd.run_cmd()
  File "/home/heath/Downloads/abmatt/abmatt/command.py", line 769, in run_cmd
    return self.run_convert()
  File "/home/heath/Downloads/abmatt/abmatt/command.py", line 837, in run_convert
    mdl = converter.load_model(model)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 48, in load_model
    self.__encode_geometry(x)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_dae.py", line 145, in __encode_geometry
    super()._encode_geometry(geometry)
  File "/home/heath/Downloads/abmatt/abmatt/converters/convert_lib.py", line 328, in _encode_geometry
    return geometry.encode(self.mdl0, encoder=encoder,
  File "/home/heath/Downloads/abmatt/abmatt/converters/geometry.py", line 118, in encode
    data, p.face_count, p.facepoint_count = self.__encode_tris(tris, p.has_weights())
  File "/home/heath/Downloads/abmatt/abmatt/converters/geometry.py", line 207, in __encode_tris
    tristrips, face_count, facepoint_count, tris = triset.get_tri_strips(fmt_str)
  File "/home/heath/Downloads/abmatt/abmatt/converters/triangle.py", line 128, in get_tri_strips
    face_point_count += encode_triangles(disconnected, fmt_str, tristrips)
  File "/home/heath/Downloads/abmatt/abmatt/converters/triangle.py", line 59, in encode_triangles
    byte_array.extend(pack('>BH', 0x90, face_point_len))
struct.error: 'H' format requires 0 <= number <= 65535
```
[model.zip](https://github.com/Robert-N7/abmatt/files/6962056/model.zip)

**Comment by Heath123** [comment]
![image](https://user-images.githubusercontent.com/13787163/129484222-a5bd7d59-b56f-4a15-b592-d5b9829a627a.png)
https://wiki.tockdom.com/wiki/Talk:Custom_Track_Tutorial#Graphic_bug_in_some_of_my_custom_tracks
So I guess that's expected
